trigger:
  - main

pool:
  vmImage: 'windows-latest' # Build agents must be Windows-based

steps:
# 1. Ensure the UiPath CLI toolset is installed on the agent
- task: UiPathInstallPlatform@3
  inputs:
    cliVersion: '24.10.0'

# 2. Package your UiPath Test Automation Project
- task: UiPathPack@3
  inputs:
    projectJsonPath: '$(Build.SourcesDirectory)/project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)'
    outputType: 'Tests' # Set type specifically to Tests

# 3. Deploy the package into your Test Orchestrator
- task: UiPathDeploy@3
  inputs:
    orchestratorConnection: 'UiPath-TestCloud-Conn'
    folderName: 'Shared/Testing'
    packagePath: '$(Build.ArtifactStagingDirectory)'

# 4. Trigger and execute your Test Cases
- task: UiPathTest@3
  inputs:
    orchestratorConnection: 'UiPath-TestCloud-Conn'
    folderName: 'Shared/Testing'
    testStrategy: 'TestSet' # Or 'TestProject' for transient runs
    testSet: 'Regression_Test_Set' # Name of pre-defined test set
    junitReportPath: '$(Build.ResultsDirectory)/test-results.xml'
